<?php


namespace Ceneo\Domain\Strategy;

use Ceneo\Domain\Model\WoocommerceCategoryWrapper;

class ExternalProductFeedGenerationStrategy extends FeedGenerationStrategy {
	public function generateProductXML( \WC_Product $product, array $wrappedCategoryPath ): string {
		return parent::generateProductXML( $product, $wrappedCategoryPath ); // TODO: Change the autogenerated stub
	}
}
